baseurl: ""
url: "https://icecold-library.github.io"

remote_theme: sylhare/Type-on-Strap

title: ICE COLD
avatar: assets/img/logos/CRREL_symbol_color.png
description: CRREL Psychrophile Library
#favicon: assets/favicon.ico
color_theme: auto # color theme auto, dark or light

header_text: CRREL Psychrophile Library
header_feature_image: "assets/img/feature-img/pexels-kristoffer-brink-jonsson-1647220.jpg"
header_feature_image_responsive: false

footer_text: Designed by <a href="https://bakerccm.github.io">@bakerccm</a> for <a href="https://www.erdc.usace.army.mil/Locations/CRREL/">CRREL</a> &copy; 2024
footer_image_credit: Banner image derived from a <a href="https://www.pexels.com/photo/body-of-water-under-gray-clouds-1647220/">photo by Kristoffer Brink Jonsson</a>

# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

