baseurl: ""
url: "https://icecold-library.github.io"

remote_theme: sylhare/Type-on-Strap

title: ICE COLD
avatar: assets/img/logos/CRREL_symbol_color.png
description: CRREL Psychrophile Library
#favicon: assets/favicon.ico
color_theme: auto # color theme auto, dark or light

header_text: CRREL Psychrophile Library
header_feature_image: "assets/img/feature-img/ice.jpg"
header_feature_image_responsive: true

footer_text: Designed by @bakerccm for CRREL &copy; 2024

# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

