baseurl: ""
url: "https://icecold-library.github.io"

remote_theme: sylhare/Type-on-Strap

title: ICE COLD                           # Name of website
#avatar: assets/img/avatar.png            # Path of avatar image, to be displayed in the theme's header
description: CRREL Psychrophile Library   # Short description, primarily used by search engines
#favicon: assets/favicon.ico              # Icon displayed in the tab
color_theme: auto                        # color theme auto, dark or light

header_text: CRREL Psychrophile Library
footer_text: Copyright 2024

#header_feature_image: assets/img/header/my-header-image.png
#header_feature_image_responsive: true

# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

